name: Github Actions Refresh

on:
  push:
    branches:
      - master
jobs:
  ime_joba:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Print Project files
        run: ls -la

      - name: Print fake build message
        run:  echo "Build started"

      - name: Print fake deploy message
        run: echo "Deploy started"

      - name: Build Docker image
        run: docker build -t gha-refresh-test:v1

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push Docker image
        run: docker push brandza99/gha-refresh-test:v1 .

